packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'

onlyBuiltDependencies:
  - '@prisma/engines'
  - electron
  - esbuild
  - prisma
  - sharp
  - tesseract.js
  - unrs-resolver
